name = "FractionalDelayFilter"
uuid = "c1b2b608-cf0a-49e8-8122-201050f5fbe7"
authors = ["hassiweb <nryk.hashimoto@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
